package db

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"go.uber.org/zap"
)

// DB wraps the database connection and provides access to generated queries
// Note: Queries type is generated by sqlc - run 'sqlc generate' first
// Queries is optional - can be nil if not using generated queries
type DB struct {
	Queries interface{} // Generated by sqlc (optional, can be nil)
	pool    *pgxpool.Pool
	logger  *zap.Logger
}

// NewDB creates a new database connection and returns a DB instance
func NewDB(dsn string, logger *zap.Logger) (*DB, error) {
	config, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("failed to parse DSN: %w", err)
	}

	pool, err := pgxpool.NewWithConfig(context.Background(), config)
	if err != nil {
		return nil, fmt.Errorf("failed to create connection pool: %w", err)
	}

	// Test connection
	if err := pool.Ping(context.Background()); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	logger.Info("Database connection established")

	return &DB{
		Queries: nil, // Queries would be generated by sqlc, but we use raw SQL
		pool:    pool,
		logger:  logger,
	}, nil
}

// Close closes the database connection pool
func (db *DB) Close() {
	if db.pool != nil {
		db.pool.Close()
		db.logger.Info("Database connection closed")
	}
}

// Ping checks if the database connection is alive
func (db *DB) Ping(ctx context.Context) error {
	return db.pool.Ping(ctx)
}

// GetPool returns the underlying connection pool
func (db *DB) GetPool() *pgxpool.Pool {
	return db.pool
}

// WithTx executes a function within a database transaction
// Note: This requires Queries to be generated by sqlc if using generated queries
func (db *DB) WithTx(ctx context.Context, fn func(interface{}) error) error {
	tx, err := db.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// For now, pass nil since we're not using generated queries
	// If using generated queries, would call: q := New(tx)
	if err := fn(nil); err != nil {
		return err
	}

	return tx.Commit(ctx)
}

// GetSQLDB returns a *sql.DB for compatibility with golang-migrate
func (db *DB) GetSQLDB() (*sql.DB, error) {
	config := db.pool.Config()
	dsn := stdlib.RegisterConnConfig(config.ConnConfig)
	return sql.Open("pgx", dsn)
}

